name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *' # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "anishde12020/action-hashnode-blog@remove-edited-if-doesnt-exist"
        with:
          USERNAME: 'avneesh0612' # Hashnode Username
          COUNT: 3 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://blog.avneesh.tech/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}